import "./globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header/header";

export const metadata: Metadata = {
  title: "NextJS Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={GeistSans.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Header />

          <main className="flex min-h-screen flex-col items-center justify-between p-6 sm:px-24">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
