import { GeistSans } from 'geist/font';
import '@/styles/globals.css';
import MainNavigation from '#components/layout/main-navigation';


export const metadata = {
  title: 'Next.js Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body>
        <MainNavigation />

        <main>{children}</main>
      </body>
    </html>
  )
}
