import { Inter } from 'next/font/google'
import '@/styles/globals.css';
import MainNavigation from './components/layout/main-navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainNavigation />

        <main>{children}</main>
      </body>
    </html>
  )
}
